spring.application.name=Sentinela2

# H2 em memória
spring.datasource.url=jdbc:h2:mem:algolpes;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Thymeleaf
spring.thymeleaf.cache=false

# Console do H2 (opcional, mas útil para ver os dados)
spring.h2.console.enabled=true